
server:
  port: 8801


logging:
  config: classpath:log4j2.yml


kafka:
  consumer:
    bootstrap.servers: 172.16.100.193:9092
    topic: hes-sae-group-0
    group.id: hansight-sae-performance
    enable.auto.commit: true
    auto.commit.interval.ms: 30000
    max.poll.records: 10000
    fetch.min.bytes: 1
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer


engine:
  multi_thread: false
  metric_on: true
  metric_period: 10


performance:
  count: 1
  epl:
    - SELECT * FROM GlobalEvent(event_name='网络连接1').win:ext_timed(occur_time,1 min) AS A GROUP BY A.`src_address` HAVING count(*) >= 10
    #- SELECT * FROM GlobalEvent(event_name='网络连接2' and src_port between 2000 and 4000).win:ext_timed(occur_time,20 min) AS A GROUP BY A.`src_address` HAVING count(*) >= 20
    #- SELECT * FROM GlobalEvent(event_name='网络连接3' and src_port between 300 and 3000).win:ext_timed(occur_time,30 min) AS A GROUP BY A.`src_address` HAVING count(*) >= 30
    #- SELECT * FROM GlobalEvent(event_name='网络连接4' and src_port between 3000 and 6000).win:ext_timed(occur_time,40 min) AS A GROUP BY A.`src_address` HAVING count(*) >= 40
    #- SELECT * FROM GlobalEvent(event_name='网络连接5' and src_port between 1000 and 5000).win:ext_timed(occur_time,50 min) AS A GROUP BY A.`src_address` HAVING count(*) >= 50
    #- SELECT * FROM GlobalEvent(event_name='网络连接6' and src_port between 2000 and 6000).win:ext_timed(occur_time,60 min) AS A GROUP BY A.`src_address` HAVING count(*) >= 60

